/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    news: News;
    'blog-posts': BlogPost;
    albums: Album;
    'gallery-categories': GalleryCategory;
    videos: Video;
    'video-categories': VideoCategory;
    newsletters: Newsletter;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    news: NewsSelect<false> | NewsSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    albums: AlbumsSelect<false> | AlbumsSelect<true>;
    'gallery-categories': GalleryCategoriesSelect<false> | GalleryCategoriesSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    'video-categories': VideoCategoriesSelect<false> | VideoCategoriesSelect<true>;
    newsletters: NewslettersSelect<false> | NewslettersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Articles, press coverage and announcements.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: string;
  title: string;
  /**
   * Used for ordering.
   */
  publishedDate: string;
  /**
   * Optional. Overrides how the date is printed, e.g. "2024" or "18 August, 2026". Leave blank to format the date above.
   */
  dateLabel?: string | null;
  /**
   * Who published it — "HPRC", "LA POLO", "Deccan Chronicle".
   */
  source?: string | null;
  /**
   * Shown as a tag — "Results", "Championship", "International".
   */
  category?: string | null;
  /**
   * The summary shown on cards and the news index.
   */
  excerpt: string;
  /**
   * Pin as the lead story on the news index. If several are ticked, the most recent wins.
   */
  featured?: boolean | null;
  /**
   * Press mentions usually link out. Choose 'Full article' to write the story here.
   */
  linkType: 'internal' | 'external';
  /**
   * URL path segment. The article appears at /events/news/<slug>.
   */
  slug?: string | null;
  /**
   * Full URL including https://
   */
  externalUrl?: string | null;
  /**
   * Preferred. Uploaded through the media library.
   */
  heroImage?: (string | null) | Media;
  /**
   * Legacy path for images that already live in /public (e.g. /documents/news/...). Only used when no upload is set above. Existing articles use this; new ones should upload instead.
   */
  heroImagePath?: string | null;
  /**
   * Build the article from blocks. Empty for link-only entries.
   */
  body?: (RichTextBlock | ImageGalleryBlock | QuoteBlock | EmbedBlock)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Describe the image for screen readers and SEO. Required.
   */
  alt: string;
  /**
   * Photographer or source, shown as a caption where the design allows.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageGalleryBlock".
 */
export interface ImageGalleryBlock {
  /**
   * Optional heading shown above the grid.
   */
  heading?: string | null;
  columns?: ('2' | '3' | '4') | null;
  /**
   * Drag to reorder.
   */
  images: {
    /**
     * Preferred. Alt text comes from the media library.
     */
    image?: (string | null) | Media;
    /**
     * Path to an image already in /public. Only used when no upload is set.
     */
    legacyPath?: string | null;
    /**
     * Required when using a legacy path.
     */
    alt?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageGallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuoteBlock".
 */
export interface QuoteBlock {
  quote: string;
  attribution?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'quote';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmbedBlock".
 */
export interface EmbedBlock {
  provider: 'youtube' | 'instagram';
  /**
   * YouTube video ID (the part after v=) or the Instagram post code from /p/<code>/.
   */
  embedId: string;
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'embed';
}
/**
 * Longer editorial pieces — riding advice, club stories.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: string;
  title: string;
  /**
   * URL path segment. The post appears at /events/blogs/<slug>.
   */
  slug: string;
  publishedDate: string;
  author?: string | null;
  /**
   * e.g. "Health & Wellness"
   */
  category?: string | null;
  /**
   * Shown on the card, e.g. "5 min read".
   */
  readTime?: string | null;
  excerpt: string;
  /**
   * Show as the lead post on the blog index.
   */
  featured?: boolean | null;
  heroImage?: (string | null) | Media;
  /**
   * Legacy path under /public. Only used when no upload is set above.
   */
  heroImagePath?: string | null;
  body: (RichTextBlock | ImageGalleryBlock | QuoteBlock | EmbedBlock)[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Photo albums shown on the gallery page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "albums".
 */
export interface Album {
  id: string;
  title: string;
  /**
   * Album id used in the page's URL hash.
   */
  slug: string;
  category: string | GalleryCategory;
  /**
   * e.g. "2016". Used for the year filter.
   */
  year?: string | null;
  /**
   * Printed verbatim, e.g. "11 Oct 2015".
   */
  date?: string | null;
  cover?: {
    /**
     * Preferred. Alt text and sizes come from the media library.
     */
    image?: (string | null) | Media;
    /**
     * Path to a file already in /public. Only used when no upload is set.
     */
    imagePath?: string | null;
  };
  /**
   * Drag to reorder. The first photo is used if no cover is set.
   */
  images?:
    | {
        /**
         * Preferred. Alt text and sizes come from the media library.
         */
        image?: (string | null) | Media;
        /**
         * Path to a file already in /public. Only used when no upload is set.
         */
        imagePath?: string | null;
        /**
         * Alt text for the legacy path above. Ignored when an upload is used.
         */
        imageAlt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Lower numbers appear first.
   */
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-categories".
 */
export interface GalleryCategory {
  id: string;
  name: string;
  /**
   * Used as the tab id on the gallery page.
   */
  slug: string;
  description?: string | null;
  /**
   * Lower numbers appear first.
   */
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Videos from the HPRC YouTube channel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: string;
  title: string;
  description?: string | null;
  /**
   * Just the ID — the part after v= in the URL. For https://youtu.be/OqYb2gZm0lk it is OqYb2gZm0lk.
   */
  youtubeId: string;
  /**
   * e.g. "1:07:00"
   */
  duration?: string | null;
  /**
   * Printed verbatim, e.g. "2.4K"
   */
  views?: string | null;
  /**
   * Leave empty for a featured video that sits above the categories.
   */
  category?: (string | null) | VideoCategory;
  /**
   * Show large, above the category sections.
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video-categories".
 */
export interface VideoCategory {
  id: string;
  name: string;
  slug: string;
  /**
   * A single emoji shown beside the category name, e.g. 🏇
   */
  icon?: string | null;
  /**
   * Lower numbers appear first.
   */
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletters".
 */
export interface Newsletter {
  id: string;
  title: string;
  /**
   * Printed verbatim, e.g. "October 2015" or "2016".
   */
  date: string;
  description?: string | null;
  /**
   * Upload the newsletter PDF. Preferred for anything new.
   */
  pdf?: (string | null) | Media;
  /**
   * Legacy path under /public/documents/newsletters/. Only used when no PDF is uploaded above.
   */
  pdfPath?: string | null;
  cover?: {
    /**
     * Preferred. Alt text and sizes come from the media library.
     */
    image?: (string | null) | Media;
    /**
     * Path to a file already in /public. Only used when no upload is set.
     */
    imagePath?: string | null;
  };
  /**
   * Lower numbers appear first.
   */
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  /**
   * Admins manage users and site settings. Editors manage content.
   */
  roles: ('admin' | 'editor')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'news';
        value: string | News;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: string | BlogPost;
      } | null)
    | ({
        relationTo: 'albums';
        value: string | Album;
      } | null)
    | ({
        relationTo: 'gallery-categories';
        value: string | GalleryCategory;
      } | null)
    | ({
        relationTo: 'videos';
        value: string | Video;
      } | null)
    | ({
        relationTo: 'video-categories';
        value: string | VideoCategory;
      } | null)
    | ({
        relationTo: 'newsletters';
        value: string | Newsletter;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  publishedDate?: T;
  dateLabel?: T;
  source?: T;
  category?: T;
  excerpt?: T;
  featured?: T;
  linkType?: T;
  slug?: T;
  externalUrl?: T;
  heroImage?: T;
  heroImagePath?: T;
  body?:
    | T
    | {
        richText?: T | RichTextBlockSelect<T>;
        imageGallery?: T | ImageGalleryBlockSelect<T>;
        quote?: T | QuoteBlockSelect<T>;
        embed?: T | EmbedBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageGalleryBlock_select".
 */
export interface ImageGalleryBlockSelect<T extends boolean = true> {
  heading?: T;
  columns?: T;
  images?:
    | T
    | {
        image?: T;
        legacyPath?: T;
        alt?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuoteBlock_select".
 */
export interface QuoteBlockSelect<T extends boolean = true> {
  quote?: T;
  attribution?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmbedBlock_select".
 */
export interface EmbedBlockSelect<T extends boolean = true> {
  provider?: T;
  embedId?: T;
  caption?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedDate?: T;
  author?: T;
  category?: T;
  readTime?: T;
  excerpt?: T;
  featured?: T;
  heroImage?: T;
  heroImagePath?: T;
  body?:
    | T
    | {
        richText?: T | RichTextBlockSelect<T>;
        imageGallery?: T | ImageGalleryBlockSelect<T>;
        quote?: T | QuoteBlockSelect<T>;
        embed?: T | EmbedBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "albums_select".
 */
export interface AlbumsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  year?: T;
  date?: T;
  cover?:
    | T
    | {
        image?: T;
        imagePath?: T;
      };
  images?:
    | T
    | {
        image?: T;
        imagePath?: T;
        imageAlt?: T;
        id?: T;
      };
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-categories_select".
 */
export interface GalleryCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  youtubeId?: T;
  duration?: T;
  views?: T;
  category?: T;
  featured?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video-categories_select".
 */
export interface VideoCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  icon?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletters_select".
 */
export interface NewslettersSelect<T extends boolean = true> {
  title?: T;
  date?: T;
  description?: T;
  pdf?: T;
  pdfPath?: T;
  cover?:
    | T
    | {
        image?: T;
        imagePath?: T;
      };
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}